- set_fact:
    ansible_user_dir: "{{ lookup('env', 'HOME') }}"
    rails_version: "7.1.3.2"  # Set your desired Rails version here or use 7.1.3


- name: Check if Ruby is installed for install bundler
  shell: "ruby -v"
  register: ruby_check
  changed_when: false
  ignore_errors: true

- name: Install Bundler
  shell: |
    {{ ansible_user_dir }}/.rbenv/shims/gem install bundler --no-document
  when: ruby_installed

- name: Install Rails
  shell: |
    {{ ansible_user_dir }}/.rbenv/shims/gem install rails -v '{{ rails_version }}' --no-document
  when: ruby_installed
