- name: Check if Ruby is installed for install bundler
  shell: "ruby -v"
  register: ruby_installed
  changed_when: false
  ignore_errors: true

- debug:
    msg: "{{ ruby_installed.stdout }}"
  when: ruby_installed

- name: Update gems
  shell: |
    {{ ansible_user_dir }}/.rbenv/shims/gem update --system
  register: gem_update_status
  when: ruby_installed

- debug:
    msg: "{{ gem_update_status.stdout }}"
  when: ruby_installed

- name: Install Bundler
  shell: |
    {{ ansible_user_dir }}/.rbenv/shims/gem install bundler --no-document
  when: ruby_installed

- name: Install pg for postgresql
  shell: |
    {{ ansible_user_dir }}/.rbenv/shims/gem install bundler --no-document
  when: ruby_installed

- name: Install Rails {{ rails_version }}
  shell: |
    {{ ansible_user_dir }}/.rbenv/shims/gem install rails -v '{{ rails_version }}' --no-document
  when: ruby_installed
