---
required_packages:
  - git
  - curl
  - libssl-dev
  - libreadline-dev
  - zlib1g-dev
  - autoconf
  - bison
  - build-essential
  - libyaml-dev
  - libffi-dev
  - libgdbm-dev
  - libncurses5-dev
  - libsqlite3-dev
  - libtool
  - pkg-config
  - sqlite3

ansible_user_dir: "{{ lookup('env', 'HOME') }}"
rbenv_root: ~/.rbenv

shell_executable_default: "/bin/bash"  # Set default shell executable to /bin/bash
shell_type_default: "bash"  # Set default shell type to bash
ruby_version: "3.3.0"
ruby_install_dir: "{{ rbenv_root }}/versions/{{ ruby_version }}"

shell_type: "{{ shell_type_default | default(omit) }}"  # Use default value if not defined
shell_config_file: "{{ ansible_user_dir }}/.{{ shell_type }}rc"
