---
- name: Check if psql is installed
  command: "psql --version"
  register: psql_check
  changed_when: false
  ignore_errors: true

- name: Install dependencies for PostgreSQL
  apt:
    name:
      - bash
      - openssl
      - libssl-dev
      - libssl-doc
    update_cache: yes
    state: latest
  when: psql_check.rc != 0

- name: Install PostgreSQL
  apt:
    name: "postgresql-{{ postgresql_version }}"
    update_cache: yes
    state: latest
  when: psql_check.rc != 0

- name: Start and enable PostgreSQL service
  systemd:
    name: postgresql
    state: started
    enabled: yes
  when: psql_check.rc != 0

- name: Ensure user has access to PostgreSQL as a superuser
  become: true
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: SUPERUSER
    state: present
  when: psql_check.rc != 0

