- hosts: localhost
  become: yes
  tasks:
    - set_fact:
        ansible_user_dir: "{{ lookup('env', 'HOME') }}"

    - debug:
        msg: "{{ ansible_user_dir }}"

    - name: Check if initial installation flag exists
      stat:
        path: "{{ ansible_user_dir }}/initial_installed.txt"
      register: initial_installed_check

    - block:
        - name: Include role - software-common-apt and rbenv-ruby
          include_role:
            name: software-common-apt
          when: not initial_installed_check.stat.exists

        - include_role:
            name: ansible-rbenv-ruby
          when: not initial_installed_check.stat.exists

        - name: Provide message for user
          debug:
            msg: |
              Ruby and Bundler installation completed.
              Please refresh your shell manually to apply changes:
              source ~/.bashrc
              or
              exec $SHELL

        - name: Create a file to indicate initial installation
          copy:
            content: "Initial installation completed"
            dest: "{{ ansible_user_dir }}/initial_installed.txt"
          when: not initial_installed_check.stat.exists

        - name: End the play after install ruby and rbenv please source your shell for next install
          ansible.builtin.meta: end_play

      when: initial_installed_check.stat.exists|bool == false

    - include_role:
        name: ansible-bundler-rails

    - include_role:
        name: ansible-postgres
