---
- hosts: localhost
  tasks:
  - include_role:
      name: software-common-apt
  - include_role:
      name: rbenv-ruby
  - name: Provide message for user
    debug:
      msg: |
        Ruby and Bundler installation completed.
        Please refresh your shell manually to apply changes:
        source ~/.bashrc
        or
        exec $SHELL
