---
- name: Set rbenv_root variable
  set_fact:
    rbenv_root: ~/.rbenv

- name: Set default values for variables
  set_fact:
    shell_executable_default: "/bin/bash"  # Set default shell executable to /bin/bash
    shell_type_default: "bash"  # Set default shell type to bash

- name: Set ruby_version variable
  set_fact:
    ruby_version: "3.3.0"

- name: Set ruby_install_dir variable
  set_fact:
    ruby_install_dir: "{{ rbenv_root }}/versions/{{ ruby_version }}"

- name: Set shell_type variable
  set_fact:
    shell_type: "{{ shell_type_default | default(omit) }}"  # Use default value if not defined

- name: Set shell_config_file variable
  set_fact:
    shell_config_file: "{{ ansible_user_dir }}/.{{ shell_type }}rc"

- name: Clone rbenv repository
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: "{{ rbenv_root }}"
    clone: yes
    update: no

- name: Check if shell config file exists
  stat:
    path: "source {{ shell_config_file }}"
  register: shell_config_check

- name: Source shell config file if exists
  shell: "source {{ shell_config_file }}"
  args:
    executable: "{{ shell_executable }}"
  when: shell_config_check.stat.exists

- name: Clone ruby-build repository
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: "{{ rbenv_root }}/plugins/ruby-build"
    clone: yes

- name: Restart shell
  shell: "source {{ shell_type }}"
  args:
    executable: "{{ shell_executable }}"
  when: shell_config_check.stat.exists

- name: Check rbenv version
  shell: "{{ rbenv_root }}/bin/rbenv --version"
  register: rbenv_version_output

- debug:
    msg: "rbenv version is {{ rbenv_version_output.stdout }}"
