---
- name: Set rbenv_root variable
  set_fact:
    rbenv_root: ~/.rbenv

- name: Clone rbenv repository
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: "{{ rbenv_root }}"
    clone: yes
    update: no

- name: Check if .zshrc exists
  stat:
    path: ~/.zshrc
  register: zshrc_check

- name: Configure rbenv for zsh if .zshrc exists
  lineinfile:
    path: ~/.zshrc
    line: 'eval "$(~/.rbenv/bin/rbenv init - zsh)"'
    insertafter: EOF
    state: present
  when: zshrc_check.stat.exists

- name: Check if .bashrc exists
  stat:
    path: ~/.bashrc
  register: bashrc_check

- name: Configure rbenv for bash if .bashrc exists
  lineinfile:
    path: ~/.bashrc
    line: 'eval "$(~/.rbenv/bin/rbenv init - bash)"'
    insertafter: EOF
    state: present
  when: bashrc_check.stat.exists

- name: Clone ruby-build repository
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: "{{ rbenv_root }}/plugins/ruby-build"
    clone: yes

- name: Restart shell
  command: "source ~/.bashrc"
  creates: "~/.ansible_shell_restart"

- name: Check rbenv version
  shell: "{{ rbenv_root }}/bin/rbenv --version"
  register: rbenv_version_output

- debug:
    msg: "rbenv version is {{ rbenv_version_output.stdout }}"
